In [2]:
import cv2
import numpy as np
import math

In [3]:
import vision

In [4]:
vid = cv2.VideoCapture(1)

In [ ]:
while(True):
    terrain = vision.terrainFetch(vid)
    if type(terrain) != bool:
        nodes, nodeCon, maskObsDilated = terrain
        break

while(True):
    output = vision.liveFeedback(vid, nodes, nodeCon, maskObsDilated)
    if type(output) != bool:
        cv2.imshow('frame', output)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break

In [ ]:
while(True):
    img = vision.frameReader(vid)
    print(np.shape(img))
    cv2.imshow('frame', img)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break

In [6]:
while(True):
    frame = vision.frameReader(vid)
    if type(frame) == bool:
        break

    odo = vision.odoFetch(vid)
    if type(odo) != bool:
        pos = np.rint(odo[:2]).astype(np.int32)
        pos[0] = vision.fieldLengthP - pos[0]
        angle = odo[2]
        output = cv2.circle(frame, pos, 5, (0,0,255), -1)

        endLX = pos[0] + np.rint(40*math.cos(angle))
        endLY = pos[1] + np.rint(40*math.sin(angle))
        endL = np.array([endLX, endLY]).astype(np.int32)
        output = cv2.line(frame, pos, endL, (0,255,0), 3)
    cv2.imshow('frame', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break

[307194      2      1      2      1]
[307193      2      1      2      2]
[307194      2      1      2      1]
[307195      2      2      1]
[307198      2]
[307194      2      1      2      1]
[307195      2      2      1]
[307195      2      1      2]
[307194      2      2      2]
[307195      2      2      1]
[307195      2      2      1]
[307194      2      1      2      1]
[307194      2      1      2      1]
[307194      2      1      2      1]
[307193      2      1      2      2]
[307194      2      1      2      1]
[307196      2      2]
[307194      2      1      2      1]
[307194      2      1      2      1]
[307194      2      1      2      1]
[307195      2      2      1]
[307194      2      1      2      1]
[307198      2]
[307194      2      1      2      1]
[307195      2      2      1]
[307195      2      1      2]
[307194      2      1      2      1]
[307195      2      2      1]
[307195      2      2      1]
[307193      2      1      2      2]
[307193      2      1  

In [ ]:
vid.release()